---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: kohi
  name: kohi
  namespace: default
spec:
  containers:
  - image: tsanghan/kopi-teh:v1
    name: kohi
    ports:
    - containerPort: 8000
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
