---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: macchiato
  name: macchiato
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: macchiato
  type: ClusterIP
status:
  loadBalancer: {}
