---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ocha
  name: ocha
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ocha
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ocha
    spec:
      containers:
      - image: tsanghan/kopi-teh:v1
        name: kopi-teh
        ports:
        - containerPort: 8000
        resources: {}
status: {}
